import type { AnnotationPanelConfig } from "./annotationPanel";

export const developerAnnotationPanelConfig = {
  id: "developer-annotation-panel",
  mode: "developer",
  placement: "line.developerPanel",
  dropdown: {
    enabled: true,
    showTitle: true,
    title: "Annotations",
    defaultOpen: false,
    triggerPlacement: "belowLeft",
  },
  empty: "hide",
  defaultOptions: {
    density: "full",
    showCoreKindLabels: true,
    showSemanticTypeLabels: true,
    showIds: true,
    showRanges: true,
    showCounts: true,
    empty: "hide",
    maxDepth: 99,
    mapping: {
      showCoreKindLabels: true,
      showSemanticTypeLabels: true,
      showIds: true,
      showMappingType: true,
      showMappingId: true,
      showMappingImageLanguage: true,
      showMappingImageForm: true,
      showNestedImageTextLine: true,
    },
    ref: {
      showCoreKindLabels: true,
      showSemanticTypeLabels: true,
      showIds: true,
      showRefType: true,
      showRefId: true,
    },
    selectorRecord: {
      showCoreKindLabels: true,
      showSemanticTypeLabels: true,
      showIds: true,
      showRanges: true,
      showSelectorType: true,
      showSelectorId: true,
      showSelectedText: true,
    },
    selection: {
      showCoreKindLabels: true,
      showSemanticTypeLabels: true,
      showIds: true,
      showRanges: true,
      showCounts: true,
      showSelectorChips: true,
      showWholeSelectionMappings: true,
      showWholeSelectionRefs: true,
      showLocalSelectedTextMappings: true,
      showLocalSelectedTextRefs: true,
      showNestedMappingImages: true,
      maxDepth: 99,
    },
  },
  blocks: [
    {
      kind: "group",
      id: "whole-line",
      title: "Whole-line",
      children: [
        {
          kind: "source",
          id: "whole-line-refs",
          title: "Refs",
          source: "textLine.refs",
        },
        {
          kind: "source",
          id: "whole-line-text-mappings",
          title: "Text mappings",
          source: "textLine.textMappings",
        },
      ],
    },
    {
      kind: "source",
      id: "selector-record",
      title: "Selector record",
      source: "textLine.selectorRecord",
    },
    {
      kind: "source",
      id: "selected-text-mappings",
      title: "Selected text mappings",
      source: "textLine.selectedTextMappings",
    },
    {
      kind: "source",
      id: "selected-text-refs",
      title: "Selected text refs",
      source: "textLine.selectedTextRefs",
    },
    {
      kind: "source",
      id: "selections",
      title: "Selections",
      source: "textLine.selections",
    },
    {
      kind: "source",
      id: "resolved-resources",
      title: "Resolved resources",
      source: "textLine.resources",
    },
  ],
} satisfies AnnotationPanelConfig;

export const learnerAnnotationPanelConfig = {
  id: "learner-annotation-panel",
  mode: "learner",
  placement: "line.below.collapsible",
  dropdown: {
    enabled: true,
    showTitle: false,
    title: "Annotations",
    defaultOpen: false,
    triggerPlacement: "bottomRight",
  },
  empty: "hide",
  defaultOptions: {
    density: "compact",
    showCoreKindLabels: false,
    showSemanticTypeLabels: true,
    showIds: false,
    showRanges: false,
    showCounts: false,
    empty: "hide",
    maxDepth: 3,
    mapping: {
      showCoreKindLabels: false,
      showSemanticTypeLabels: true,
      showIds: false,
      showMappingType: true,
      showMappingId: false,
      showMappingImageLanguage: false,
      showMappingImageForm: false,
      showNestedImageTextLine: true,
    },
    ref: {
      showCoreKindLabels: false,
      showSemanticTypeLabels: true,
      showIds: false,
      showRefType: true,
      showRefId: false,
    },
    selectorRecord: {
      showCoreKindLabels: false,
      showSemanticTypeLabels: false,
      showIds: false,
      showRanges: false,
      showSelectorType: false,
      showSelectorId: false,
      showSelectedText: true,
    },
    selection: {
      showCoreKindLabels: false,
      showSemanticTypeLabels: true,
      showIds: false,
      showRanges: false,
      showCounts: false,
      showSelectorChips: true,
      showWholeSelectionMappings: true,
      showWholeSelectionRefs: true,
      showLocalSelectedTextMappings: true,
      showLocalSelectedTextRefs: true,
      showNestedMappingImages: true,
      maxDepth: 3,
    },
  },
  blocks: [
    {
      kind: "group",
      id: "line-annotations",
      title: "Line annotations",
      children: [
        {
          kind: "source",
          id: "learner-line-refs",
          title: "Refs",
          source: "textLine.refs",
          filter: {
            refTypes: ["tag", "note", "dictionary"],
          },
        },
        {
          kind: "source",
          id: "learner-line-mappings",
          title: "Translations",
          source: "textLine.textMappings",
          filter: {
            mappingTypes: ["translation"],
            languages: "currentTranslation",
          },
        },
      ],
    },
    {
      kind: "source",
      id: "learner-selections",
      title: "Selections",
      source: "textLine.selections",
      filter: {
        selectionTypes: ["decomposition", "parallel", "translationUnit"],
      },
    },
    {
      kind: "source",
      id: "learner-selected-text-mappings",
      title: "Selected text mappings",
      source: "textLine.selectedTextMappings",
      filter: {
        mappingTypes: ["gloss", "translation", "learnerHint", "form", "romanization", "transliteration"],
        languages: "any",
      },
    },
    {
      kind: "source",
      id: "learner-selected-text-refs",
      title: "Selected text refs",
      source: "textLine.selectedTextRefs",
      filter: {
        refTypes: ["note", "dictionary", "tag"],
      },
    },
  ],
} satisfies AnnotationPanelConfig;
